### PR TITLE
add servicemonitor

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/roadmap/issues/382

Add `ServiceMonitor` for the analytics-server so its scrapped by Prometheus.

### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by TheoBrigitte** [comment]
Tested and got metrics in prometheus

image

**Review by QuentinBisson — APPROVED** [review]
It seems fine to me but can you also remove the monitoring annotations to the service ?

**Comment by TheoBrigitte** [comment]
> It seems fine to me but can you also remove the monitoring annotations to the service ?

What do you want to remove `namespace=monitoring` annotation ?

**Comment by QuentinBisson** [comment]
Sorry for my lack of context. I already added the giantswarm.io/monitoring annotation on the service manifest: https://github.com/giantswarm/macropower-analytics-panel-server-app/blob/5e9e6d67f7dfa4f63ae9b8b310e262c4dcae62d3/helm/macropower-analytics-panel-server/templates/service.yaml#L8 so it needs to be removed to ensure the service monitor wors :)

**Review by QuentinBisson — APPROVED** [review]
Awesome

**Comment by TheoBrigitte** [comment]
Perfects not more duplicates :ok_hand: 

image

**Pull request merged**
