### PR TITLE
Fixup ingress-auth to use extensions/v1beta1 fields

### PR DESCRIPTION
**Pull request by mig4**
This PR:

- changes `ingress-auth` to use fields from declared `extensions/v1beta1` version

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]

**Review by TheoBrigitte — APPROVED** [review]
Oops, thanks for taking care

**Comment by mig4** [comment]
The ingress defined in `ingress-auth.yaml` and Grafana's main ingress are almost exactly the same (one difference is `nginx.ingress.kubernetes.io/rewrite-target: /` annotation on the one defined here). So I thought I'll test using Grafana's main ingress directly and it works OK, so I think this one can be removed to further simplify the setup. WDYT? @TheoBrigitte, @QuentinBisson

**Comment by QuentinBisson** [comment]
If they do the same thing, sure you can remove it :D

**Comment by TheoBrigitte** [comment]
How it this supposed to work now? The main point of the auth ingress was to forward the connection to grafana and not the analytics server, that's why it needs `rewrite-target: /`

**Comment by TheoBrigitte** [comment]
At first I had the same idea of using the annotation but this just doesn't seems to work, feel free to test it.

**Comment by mig4** [comment]
> You would actually need to put the grafana root url into the annotation, like:

Yip, you're right but because this ingress is on Grafana URL then this:

```
nginx.ingress.kubernetes.io/auth-url: https://grafana.g8s.ginger.eu-west-1.aws.gigantic.io
```

is equivalent to

```
nginx.ingress.kubernetes.io/auth-url: https://$host/
```

that way you're redirected to main Grafana ingress at `/` for authentication check, and you don't need `nginx.ingress.kubernetes.io/rewrite-target: /` because you're already at `/`.

OK, but I just realised this way we'd be adding a hidden dependency on Grafana's ingress and that is not great. Your solution is better because we ship a secondary ingress configured the way we need pointing to the backend Grafana service. I'll revert the last commit.

**Pull request merged**
