### PR TITLE
drop user labels

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/roadmap/issues/382

Drop every user related labels.

Added missing entry from CHANGELOG.

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]
Looks great

**Review by mig4 — APPROVED** [review]
🎉

**Comment by TheoBrigitte** [comment]
Following labels are gone: `user_locale`, `user_login`, `user_name`, `user_role`, `user_theme`, `user_timezone`.

image

**Comment by mig4** [comment]
Isn't `user_role` the only way we can distinguish between GS user and customer user? This was one of the requirements, see https://github.com/giantswarm/roadmap/issues/364#issuecomment-883369221

**Pull request merged**
